In [2]:
[1]
import numpy as np
list=[1,2,3]
print(list)

[1, 2, 3]


In [3]:
[2]
Array=np.array(list)
print(Array)

[1 2 3]


In [4]:
[3]
print(type(list))
print(type(Array))

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
[4]
list2=[4,5,6]
a2=np.array(list2)
a3 = Array * a2
print(a3)
print(a2/Array)

[ 4 10 18]
[4.  2.5 2. ]


In [6]:
[5]
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([3,4,5,6,7])
c=a+b
print(c)

[ 4  6  8 10 12]


In [7]:
[6]
print(np.sin(a))
print(np.log(a))
print(np.log2(a))
print(np.exp(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
